name: MTR and Curl Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  network-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y mtr curl

      - name: Run MTR tests
        run: |
          echo "Running MTR to arvancloud.ir..." > mtr_results.txt
          mtr --report --report-cycles=10 arvancloud.ir >> mtr_results.txt

          echo "\nRunning MTR to google.com..." >> mtr_results.txt
          mtr --report --report-cycles=10 google.com >> mtr_results.txt

      - name: Run Curl tests
        run: |
          echo "Running Curl to arvancloud.ir..." > curl_results.txt
          curl -I -L arvancloud.ir >> curl_results.txt

          echo "\nRunning Curl to google.com..." >> curl_results.txt
          curl -I -L google.com >> curl_results.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: network-test-results
          path: |
            mtr_results.txt
            curl_results.txt

